// SPDX-License-Identifier: MIT

import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import {
  parseProgrammeCaptureSupervisorServiceResultBlobV2,
  serializeProgrammeCaptureSupervisorServiceResultV2,
} from '../src/programme-capture-supervisor-service-result-v2.js';
import { validateStoredRegistrationResultV2 } from
  '../supervisor-service/src/registration-protocol-v2.js';
import {
  ACTIVE_HEAD, DIGEST, PROJECT, exactStoredResult,
} from '../supervisor-service/__tests__/registration-fixtures.js';

const RESULT_201_KAT_SHA256 =
  '8e3a236bddbe575a7b377d91c09a9cdd248d5913b9cfa3623936b3e903e587a5';

describe('private service and controller result interoperability V2', () => {
  it('accepts one independently generated byte-identical 201 result KAT', async () => {
    const exact = exactStoredResult(201);
    const bytes = exact.row.serializedResponse;
    expect(createHash('sha256').update(bytes, 'utf8').digest('hex'))
      .toBe(RESULT_201_KAT_SHA256);

    const parsed = parseProgrammeCaptureSupervisorServiceResultBlobV2(bytes);
    expect(serializeProgrammeCaptureSupervisorServiceResultV2(parsed)).toBe(bytes);
    await expect(validateStoredRegistrationResultV2(bytes, {
      semanticRequestDigest: DIGEST.request,
      originalRegistrationRequestDigest: DIGEST.request,
      originalRegistrationEventDigest: exact.row.originalRegistrationEventDigest,
      originalRegistrationGlobalSequence: '1',
      changedReplayPriorControllerStateHeadDigest: null,
      projectAuthorityDigest: DIGEST.project,
      principalId: PROJECT.principalId,
      runId: 'capture_run_20260829',
      authorityHead: ACTIVE_HEAD.authorityHead,
      priorControllerStateHeadDigest: DIGEST.priorController,
      claim: {
        claimKeyDigest: DIGEST.claimKey,
        claimDigest: DIGEST.claim,
        rootedClaimValidationDigest: DIGEST.rootedClaim,
      },
    }, 201)).resolves.toBeUndefined();
  });
});
