// SPDX-License-Identifier: MIT

export const PROGRAMME_V5_POST_HISTORICAL_PATHS: ReadonlySet<string> = new Set([
  'coding-harness/__tests__/programme-capture-claim-io-v1.test.ts',
  'coding-harness/__tests__/programme-capture-claim-record-v1.test.ts',
  'coding-harness/__tests__/programme-capture-git-v1.test.ts',
  'coding-harness/__tests__/programme-capture-host-capabilities-v1.test.ts',
  'coding-harness/__tests__/programme-capture-host-preflight-v1.test.ts',
  'coding-harness/__tests__/programme-capture-input-attestation-v1.test.ts',
  'coding-harness/__tests__/programme-capture-private-source-v1.test.ts',
  'coding-harness/__tests__/programme-capture-state-v1.test.ts',
  'coding-harness/__tests__/programme-capture-task-v1.test.ts',
  'coding-harness/__tests__/programme-v5-post-historical-paths.ts',
  'coding-harness/src/programme-capture-claim-io-v1.ts',
  'coding-harness/src/programme-capture-claim-record-v1.ts',
  'coding-harness/src/programme-capture-config-v1.ts',
  'coding-harness/src/programme-capture-git-v1.ts',
  'coding-harness/src/programme-capture-host-authority-v1.ts',
  'coding-harness/src/programme-capture-host-observation-v1.ts',
  'coding-harness/src/programme-capture-host-preflight-v1.ts',
  'coding-harness/src/programme-capture-input-attestation-record-v1.ts',
  'coding-harness/src/programme-capture-input-attestation-v1.ts',
  'coding-harness/src/programme-capture-private-source-fs-v1.ts',
  'coding-harness/src/programme-capture-private-source-v1.ts',
  'coding-harness/src/programme-capture-runner-profile-v1.ts',
  'coding-harness/src/programme-capture-state-v1.ts',
  'coding-harness/src/programme-capture-task-v1.ts',
  'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage.rs',
  'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/loader_output.rs',
  'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/tests.rs',
  'docs/adr/ADR-0041-manifest-bound-controlled-observational-evidence-capture.md',
]);
