// SPDX-License-Identifier: MIT

import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import {
  chmodSync,
  mkdtempSync,
  mkdirSync,
  readFileSync,
  realpathSync,
  rmSync,
  truncateSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { createSystemOfflineIsolator } from '../src/sandbox.js';
import {
  parseWritableFileOverlays,
  prepareWorkspaceFileOverlays,
} from '../src/writable-overlays.js';
import { fakeResourceBoundary, TEST_RESOURCE_LIMITS } from './helpers.js';
import { bwrapAvailable } from './native-test-prerequisites.js';

const roots: string[] = [];

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

describe('disposable writable file overlays', () => {
  it('seals generated bytes while preserving the tracked destination identity', () => {
    const fixture = makeFixture();
    const lease = prepareWorkspaceFileOverlays({
      controlledRoot: fixture.controlled,
      workspaceRoot: fixture.workspace,
      outputRoot: fixture.output,
      workspacePaths: ['reports/earl.ttl'],
    });
    const original = readFileSync(fixture.destination, 'utf8');
    const generated = validEarl();
    writeFileSync(lease.mounts[0].source, generated);

    expect(lease.seal()).toEqual({
      'reports/earl.ttl': sha256(generated),
    });
    expect(readFileSync(fixture.destination, 'utf8')).toBe(original);
  });

  it('rejects a changed tracked destination and malformed overlay maps', () => {
    const fixture = makeFixture();
    const lease = prepareWorkspaceFileOverlays({
      controlledRoot: fixture.controlled,
      workspaceRoot: fixture.workspace,
      outputRoot: fixture.output,
      workspacePaths: ['reports/earl.ttl'],
    });
    writeFileSync(fixture.destination, 'tampered\n');
    expect(() => lease.seal()).toThrow(/OVERLAY_DESTINATION_CHANGED/);
    expect(() => parseWritableFileOverlays([
      { source: fixture.destination, destination: fixture.destination },
    ], 'overlays')).toThrow(/duplicate or self/);
  });

  it('rejects stale copied or untouched report bytes', () => {
    const fixture = makeFixture();
    const lease = prepareWorkspaceFileOverlays({
      controlledRoot: fixture.controlled,
      workspaceRoot: fixture.workspace,
      outputRoot: fixture.output,
      workspacePaths: ['reports/earl.ttl'],
    });

    expect(() => lease.seal()).toThrow(/OVERLAY_NOT_GENERATED/);
  });

  it('rejects oversized originals and generated files before reading them', () => {
    const originalFixture = makeFixture();
    truncateSync(originalFixture.destination, 10_000_001);
    expect(() => prepareWorkspaceFileOverlays({
      controlledRoot: originalFixture.controlled,
      workspaceRoot: originalFixture.workspace,
      outputRoot: originalFixture.output,
      workspacePaths: ['reports/earl.ttl'],
    })).toThrow(/OVERLAY_DESTINATION_INVALID/);

    const generatedFixture = makeFixture();
    const lease = prepareWorkspaceFileOverlays({
      controlledRoot: generatedFixture.controlled,
      workspaceRoot: generatedFixture.workspace,
      outputRoot: generatedFixture.output,
      workspacePaths: ['reports/earl.ttl'],
    });
    truncateSync(lease.mounts[0].source, 10_000_001);
    expect(() => lease.seal()).toThrow(/OVERLAY_SOURCE_CHANGED/);
  });

  it('allocates independent files for consecutive producer commands', () => {
    const fixture = makeFixture();
    const input = {
      controlledRoot: fixture.controlled,
      workspaceRoot: fixture.workspace,
      outputRoot: fixture.output,
      workspacePaths: ['reports/earl.ttl'],
    };
    const first = prepareWorkspaceFileOverlays(input);
    const second = prepareWorkspaceFileOverlays(input);

    expect(second.mounts[0].source).not.toBe(first.mounts[0].source);
  });

  it('places the disposable bind after the read-only workspace bind', () => {
    const fixture = makeFixture();
    const lease = prepareWorkspaceFileOverlays({
      controlledRoot: fixture.controlled,
      workspaceRoot: fixture.workspace,
      outputRoot: fixture.output,
      workspacePaths: ['reports/earl.ttl'],
    });
    const isolator = createSystemOfflineIsolator({
      executablePath: '/usr/bin/true',
      writableRoot: fixture.controlled,
      readOnlyMounts: [{ source: '/usr/bin', destination: '/usr/bin' }],
      resourceBoundary: fakeResourceBoundary,
      resourceLimits: TEST_RESOURCE_LIMITS,
    });
    const isolated = isolator.isolate({
      executable: '/usr/bin/true',
      args: [],
      cwd: fixture.workspace,
      env: {},
      writablePaths: [fixture.output],
      writableOverlays: lease.mounts,
    }) as { command: { args: readonly string[] } };
    const workspaceBind = subsequenceIndex(isolated.command.args, [
      '--ro-bind', fixture.workspace, fixture.workspace,
    ]);
    const overlayBind = subsequenceIndex(isolated.command.args, [
      '--bind', lease.mounts[0].source, fixture.destination,
    ]);
    expect(workspaceBind).toBeGreaterThanOrEqual(0);
    expect(overlayBind).toBeGreaterThan(workspaceBind);
  });

  it.runIf(bwrapAvailable())('executes a real offline writer against only the disposable overlay', () => {
    const fixture = makeFixture();
    const lease = prepareWorkspaceFileOverlays({
      controlledRoot: fixture.controlled,
      workspaceRoot: fixture.workspace,
      outputRoot: fixture.output,
      workspacePaths: ['reports/earl.ttl'],
    });
    const isolator = createSystemOfflineIsolator({
      executablePath: realpathSync('/usr/bin/bwrap'),
      writableRoot: fixture.controlled,
      readOnlyMounts: [
        { source: '/usr/bin', destination: '/usr/bin' },
        { source: '/usr/lib', destination: '/usr/lib' },
        { source: '/usr/lib', destination: '/lib' },
        { source: '/usr/lib64', destination: '/usr/lib64' },
        { source: '/usr/lib64', destination: '/lib64' },
      ],
      resourceBoundary: fakeResourceBoundary,
      resourceLimits: TEST_RESOURCE_LIMITS,
    });
    const generated = validEarl();
    const isolated = isolator.isolate({
      executable: realpathSync('/usr/bin/dash'),
      args: ['-c', 'printf %s "$1" > "$2"', 'harness', generated, fixture.destination],
      cwd: fixture.workspace,
      env: {},
      writablePaths: [fixture.output],
      writableOverlays: lease.mounts,
    }) as { command: { executable: string; args: readonly string[]; env: NodeJS.ProcessEnv } };
    const result = spawnSync(isolated.command.executable, [...isolated.command.args], {
      cwd: fixture.workspace,
      env: isolated.command.env,
      encoding: 'utf8',
    });

    expect(result.status, result.stderr).toBe(0);
    expect(lease.seal()).toEqual({ 'reports/earl.ttl': sha256(generated) });
    expect(readFileSync(fixture.destination, 'utf8')).toBe('tracked report\n');
  });
});

function makeFixture() {
  const controlled = mkdtempSync(join(tmpdir(), 'coding-harness-overlays-'));
  roots.push(controlled);
  chmodSync(controlled, 0o700);
  const workspace = join(controlled, 'workspace');
  const output = join(controlled, 'output');
  mkdirSync(join(workspace, 'reports'), { recursive: true });
  mkdirSync(output, { mode: 0o700 });
  const destination = join(workspace, 'reports/earl.ttl');
  writeFileSync(destination, 'tracked report\n');
  return { controlled, workspace, output, destination };
}

function sha256(value: string): string {
  return createHash('sha256').update(value).digest('hex');
}

function validEarl(): string {
  return '@prefix earl: <http://www.w3.org/ns/earl#> .\n'
    + '[] a earl:Assertion ;\n'
    + '  earl:subject <https://example.org/tools/semantic-fabric> ;\n'
    + '  earl:result [ earl:outcome earl:passed ] .\n';
}

function subsequenceIndex(values: readonly string[], sequence: readonly string[]): number {
  for (let index = 0; index <= values.length - sequence.length; index += 1) {
    if (sequence.every((value, offset) => values[index + offset] === value)) return index;
  }
  return -1;
}
