// SPDX-License-Identifier: MIT

import { APPROVED_NPM_REGISTRY, parseHarnessConfig } from './contracts.js';
import {
  PROGRAMME_CAPTURE_SOURCE_PROTECTED_PATHS_V1,
  PROGRAMME_CAPTURE_SUPERVISOR_SERVICE_PACKAGE_PROTECTED_PATHS_V1,
  PROGRAMME_CAPTURE_TEST_SUPPORT_PROTECTED_PATHS_V1,
  PROGRAMME_CAPTURE_TEST_PROTECTED_PATHS_V1,
} from './programme-capture-protected-paths-v1.js';

export const SECURE_HARNESS_CONFIG = parseHarnessConfig({
  schemaVersion: 1,
  authority: 'development-only-no-promotion',
  approvedRegistry: APPROVED_NPM_REGISTRY,
  firstPartyOrigins: [
    'https://api.anthropic.com',
    'https://api.openai.com',
    'https://chatgpt.com',
    'https://claude.ai',
  ],
  allowedTools: ['read_file', 'write_file', 'apply_patch', 'git', 'node', 'npm', 'cargo', 'rustc'],
  requiredProtectedPaths: [
    '.cargo/audit.toml',
    '.claude-flow/harness-active-policy.json',
    '.claude/.proven-config-version',
    '.claude/eval/flywheel-anchor.manifest.json',
    '.claude/eval/semantic-fabric-relevance-anchor-v1.json',
    '.claude/proven-config.json',
    '.claude/settings.json',
    '.github/workflows/ci.yml',
    '.github/workflows/harness-native.yml',
    '.gitignore',
    '.harness/mcp-policy.json',
    '.mcp.json',
    'AGENTS.md',
    'BENCHMARKS.md',
    'CLAUDE.md',
    'COMPARISON.md',
    'Cargo.lock',
    'Cargo.toml',
    'LICENSE-APACHE',
    'LICENSE-MIT',
    'README.md',
    'coding-harness/__tests__/m0-authority.test.ts',
    ...PROGRAMME_CAPTURE_TEST_PROTECTED_PATHS_V1,
    ...PROGRAMME_CAPTURE_TEST_SUPPORT_PROTECTED_PATHS_V1,
    'coding-harness/__tests__/programme-envelope-v5.test.ts',
    'coding-harness/__tests__/programme-policy-v5.test.ts',
    'coding-harness/__tests__/programme-v5-post-historical-paths.ts',
    'coding-harness/.claude-plugin/plugin.json',
    'coding-harness/.harness/controller-build.json',
    'coding-harness/.harness/manifest.json',
    'coding-harness/CLAUDE.md',
    'coding-harness/LICENSE',
    'coding-harness/README.md',
    'coding-harness/config/issue-8-baseline-Cargo.lock.gz.b64',
    'coding-harness/config/issue-8-acceptance.json',
    'coding-harness/config/metaharness-diagnostics.json',
    'coding-harness/config/programme-v5-acceptance.json',
    'coding-harness/package.json',
    'coding-harness/package-lock.json',
    'coding-harness/scripts/deny-publish.mjs',
    'coding-harness/scripts/harden-build.mjs',
    'coding-harness/scripts/launch-issue-8.mjs',
    'coding-harness/scripts/launch-programme-v5.mjs',
    'coding-harness/scripts/launch-programme-v6.mjs',
    'coding-harness/scripts/programme-v5-operator-support.mjs',
    'coding-harness/scripts/programme-v6-operator-support.mjs',
    'coding-harness/scripts/run-programme-v5.mjs',
    'coding-harness/scripts/run-programme-v6.mjs',
    'coding-harness/src/agents/architect.ts',
    'coding-harness/src/agents/implementer.ts',
    'coding-harness/src/agents/reviewer.ts',
    'coding-harness/src/agents/test-writer.ts',
    'coding-harness/src/agentic-qe-lcov.ts',
    'coding-harness/src/agentic-qe-lcov-response.ts',
    'coding-harness/src/agentic-qe-mcp-identity.ts',
    'coding-harness/src/agentic-qe-mcp-protocol.ts',
    'coding-harness/src/agentic-qe-mcp-request.ts',
    'coding-harness/src/agentic-qe-mcp-runner.ts',
    'coding-harness/src/agentic-qe-sast.ts',
    'coding-harness/src/agentic-qe-sast-response.ts',
    'coding-harness/src/acceptance-task.ts',
    'coding-harness/src/acceptance-task-v3.ts',
    'coding-harness/src/acceptance-runner.ts',
    'coding-harness/src/candidate-finish.ts',
    'coding-harness/src/candidate-repair-transition.ts',
    'coding-harness/src/candidate-transaction-evidence-v1.ts',
    'coding-harness/src/candidate.ts',
    'coding-harness/src/candidate-types.ts',
    'coding-harness/src/candidate-gates.ts',
    'coding-harness/src/candidate-receipt-evidence.ts',
    'coding-harness/src/config.ts',
    'coding-harness/src/contracts.ts',
    'coding-harness/src/controller-attestation.ts',
    'coding-harness/src/controller-build.ts',
    'coding-harness/src/evidence.ts',
    'coding-harness/src/effective-config.ts',
    'coding-harness/src/effective-config-command.ts',
    'coding-harness/src/effective-config-diagnostics.ts',
    'coding-harness/src/effective-config-filesystem.ts',
    'coding-harness/src/effective-config-git.ts',
    'coding-harness/src/evaluator.ts',
    'coding-harness/src/failure-code.ts',
    'coding-harness/src/frozen-cargo-lock-fixture.ts',
    'coding-harness/src/frozen-cargo-lock.ts',
    'coding-harness/src/frozen-cargo-metadata.ts',
    'coding-harness/src/git-materialization.ts',
    'coding-harness/src/git-process.ts',
    'coding-harness/src/git-protected-boundary.ts',
    'coding-harness/src/git-worktrees.ts',
    'coding-harness/src/immutable-private-runtime.ts',
    'coding-harness/src/independent-rust-lcov.ts',
    'coding-harness/src/index.ts',
    'coding-harness/src/issue-8-driver.ts',
    'coding-harness/src/issue-8-native-session.ts',
    'coding-harness/src/issue-8-program.ts',
    'coding-harness/src/issue-8-programme-envelope.ts',
    'coding-harness/src/issue-8-rust-runtime.ts',
    'coding-harness/src/issue-8-qe.ts',
    'coding-harness/src/issue-8-system.ts',
    'coding-harness/src/issue-8-v2-evidence.ts',
    'coding-harness/src/kernel.ts',
    'coding-harness/src/manifest.ts',
    'coding-harness/src/metadata-tree.ts',
    'coding-harness/src/metaharness-diagnostics.ts',
    'coding-harness/src/model-context.ts',
    'coding-harness/src/model-controller.ts',
    'coding-harness/src/native-client.ts',
    'coding-harness/src/native-patch-output.ts',
    'coding-harness/src/native-egress-audit.ts',
    'coding-harness/src/native-egress.ts',
    'coding-harness/src/native-filesystem.ts',
    'coding-harness/src/native-proxy-launcher.cts',
    'coding-harness/src/native-proxy-launcher.ts',
    'coding-harness/src/native-system-filesystem.ts',
    'coding-harness/src/models/environment.ts',
    'coding-harness/src/models/index.ts',
    'coding-harness/src/models/native-adapters.ts',
    'coding-harness/src/models/native-adapter-contracts.ts',
    'coding-harness/src/models/recovery.ts',
    'coding-harness/src/models/review.ts',
    'coding-harness/src/models/routing.ts',
    'coding-harness/src/models/types.ts',
    'coding-harness/src/native-process.ts',
    'coding-harness/src/native-process-contracts.ts',
    'coding-harness/src/native-process-execution.ts',
    'coding-harness/src/native-runtime-evidence-v2.ts',
    'coding-harness/src/native-runtime-ledger.ts',
    'coding-harness/src/native-runtime.ts',
    'coding-harness/src/network.ts',
    'coding-harness/src/policy.ts',
    'coding-harness/src/parallel.ts',
    'coding-harness/src/programme-acceptance.ts',
    ...PROGRAMME_CAPTURE_SOURCE_PROTECTED_PATHS_V1,
    'coding-harness/src/programme-envelope.ts',
    'coding-harness/src/programme-envelope-v5.ts',
    'coding-harness/src/programme-envelope-v6.ts',
    'coding-harness/src/programme-gate-contract-v1.ts',
    'coding-harness/src/programme-gate-contract-v2.ts',
    'coding-harness/src/programme-gates-v5.ts',
    'coding-harness/src/programme-gates-v6.ts',
    'coding-harness/src/programme-policy-v5.ts',
    'coding-harness/src/programme-policy-v6.ts',
    'coding-harness/src/programme-receipt-keys.ts',
    'coding-harness/src/programme-score-v5.ts',
    'coding-harness/src/programme-task-runtime-v1.ts',
    'coding-harness/src/programme-v5-driver-support.ts',
    'coding-harness/src/programme-v5-driver.ts',
    'coding-harness/src/programme-v5-policy-anchor.ts',
    'coding-harness/src/programme-v5-program-runtime.ts',
    'coding-harness/src/programme-v5-program.ts',
    'coding-harness/src/programme-v5-qe.ts',
    'coding-harness/src/programme-v5-receipt-io.ts',
    'coding-harness/src/programme-v5-replay.ts',
    'coding-harness/src/programme-v5-ruflo-contract.ts',
    'coding-harness/src/programme-v5-ruflo-runtime.ts',
    'coding-harness/src/programme-v5-ruflo.ts',
    'coding-harness/src/programme-v5-system.ts',
    'coding-harness/src/programme-v6-base-execution.ts',
    'coding-harness/src/programme-v6-policy-anchor.ts',
    'coding-harness/src/programme-v6-program.ts',
    'coding-harness/src/programme-v6-receipt-io.ts',
    'coding-harness/src/programme-v6-replay.ts',
    'coding-harness/src/qe-profile.ts',
    'coding-harness/src/process.ts',
    'coding-harness/src/receipts.ts',
    'coding-harness/src/resource-boundary.ts',
    'coding-harness/src/resource-cleanup.ts',
    'coding-harness/src/repository-operations.ts',
    'coding-harness/src/repository-command-evidence.ts',
    'coding-harness/src/repository-command-runner.ts',
    'coding-harness/src/repository-options.ts',
    'coding-harness/src/rust-closure.ts',
    'coding-harness/src/rust-registry-closure.ts',
    'coding-harness/src/rust-sandbox.ts',
    'coding-harness/src/sandbox.ts',
    'coding-harness/src/strict-json.ts',
    'coding-harness/src/task-evidence-plan.ts',
    'coding-harness/src/task-qe.ts',
    'coding-harness/src/verifier-failure.ts',
    'coding-harness/src/workspace.ts',
    'coding-harness/src/writable-overlays.ts',
    ...PROGRAMME_CAPTURE_SUPERVISOR_SERVICE_PACKAGE_PROTECTED_PATHS_V1,
    'coding-harness/tsconfig.json',
    'coding-harness/vitest.config.ts',
    'crates/sf-bench/Cargo.toml',
    'crates/sf-bench/config/performance-scenarios-v1.tsv',
    'crates/sf-bench/src/bin/sf-performance-receipt.rs',
    'crates/sf-bench/src/driver.rs',
    'crates/sf-bench/src/lib.rs',
    'crates/sf-bench/src/mem.rs',
    'crates/sf-bench/src/performance/bounded_io.rs',
    'crates/sf-bench/src/performance/capture.rs',
    'crates/sf-bench/src/performance/compare.rs',
    'crates/sf-bench/src/performance/config.rs',
    'crates/sf-bench/src/performance/digest.rs',
    'crates/sf-bench/src/performance/format.rs',
    'crates/sf-bench/src/performance/mod.rs',
    'crates/sf-bench/src/performance/model.rs',
    'crates/sf-bench/src/performance/paths.rs',
    'crates/sf-bench/src/performance/proc_status.rs',
    'crates/sf-bench/src/performance/producer.rs',
    'crates/sf-bench/src/performance/profile.rs',
    'crates/sf-bench/src/performance/source.rs',
    'crates/sf-bench/src/performance/stats.rs',
    'crates/sf-bench/src/performance/subprocess.rs',
    'crates/sf-bench/src/performance/worker.rs',
    'crates/sf-bench/src/performance/workload_runner.rs',
    'crates/sf-bench/src/workload.rs',
    'crates/sf-bench/tests/performance_capture.rs',
    'crates/sf-bench/tests/performance_cli.rs',
    'crates/sf-bench/tests/performance_paths.rs',
    'crates/sf-bench/tests/performance_platform.rs',
    'crates/sf-bench/tests/performance_profile.rs',
    'crates/sf-bench/tests/performance_receipt.rs',
    'crates/sf-bench/tests/performance_stats.rs',
    'crates/sf-bench/tests/performance_subprocess.rs',
    'crates/sf-cli/Cargo.toml',
    'crates/sf-conformance/Cargo.toml',
    'crates/sf-conformance/src/bin/capability-matrix.rs',
    'crates/sf-conformance/src/bin/current-sf-cli-artifact-observation.rs',
    'crates/sf-conformance/src/bin/rdb2rdf-execution-receipt.rs',
    'crates/sf-conformance/src/bin/rdb2rdf-inventory.rs',
    'crates/sf-conformance/src/bin/rust-closure-receipt.rs',
    'crates/sf-conformance/src/bin/sparql-protocol-regression-baseline.rs',
    'crates/sf-conformance/src/bin/sparql-query-regression-baseline.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/authority.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/authority_guard.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/artifact_pair.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/capture.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/cargo.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/elf.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/format.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/format/records.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/host_link_authority.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/host_link_authority/tests.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/linker.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/linker/capture_tests.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/mod.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/model.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/model/link.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/process.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/process/capture.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/process/execveat.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/producer.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/producer_paths.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/producer_paths/link_input.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/receipt_file.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_elf.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_elf/policy.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_elf/program.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_elf/program_policy.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_elf/tests.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_elf/tests/policy.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_elf/tests/program.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_elf/tests/versioning.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_elf/versioning.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/bwrap_resolution_inventory.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/bwrap_resolution_inventory/format.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/bwrap_resolution_inventory/tests.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/loader_output.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/linux.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/linux/component.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/linux/logical_path.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/linux/sealed.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/prepared_probe.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/prepared_probe/bindings.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/prepared_probe/policy.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/prepared_probe/receipt.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/prepared_probe/resolution.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/prepared_probe/seccomp.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/prepared_probe/tool.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/tests.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/tests/adversarial.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/tests/bwrap_resolution.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/tests/prepared_probe.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/tests/prepared_receipt.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/tests/prepared_seccomp.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/tests/prepared_seccomp_canary.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/tests/runtime_elf_policy.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/object_authority/tests/support.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/prepared_receipt.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/prepared_receipt/format.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/prepared_receipt/format/tests.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/prepared_receipt/tests.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/runtime_linkage/tests.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/sandbox.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/sandbox_environment.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/source.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/source_blobs.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/source_tree.rs',
    'crates/sf-conformance/src/binary_artifact_receipt/tests.rs',
    'crates/sf-conformance/src/capability_catalog.rs',
    'crates/sf-conformance/src/capability_model.rs',
    'crates/sf-conformance/src/capability_render.rs',
    'crates/sf-conformance/src/execution_receipt.rs',
    'crates/sf-conformance/src/execution_receipt/format.rs',
    'crates/sf-conformance/src/execution_receipt/tests.rs',
    'crates/sf-conformance/src/graph.rs',
    'crates/sf-conformance/src/inventory.rs',
    'crates/sf-conformance/src/inventory/format.rs',
    'crates/sf-conformance/src/inventory/policy.rs',
    'crates/sf-conformance/src/lib.rs',
    'crates/sf-conformance/src/manifest.rs',
    'crates/sf-conformance/src/oracle.rs',
    'crates/sf-conformance/src/pg.rs',
    'crates/sf-conformance/src/pg/outcome.rs',
    'crates/sf-conformance/src/pg/tests.rs',
    'crates/sf-conformance/src/regression_receipt/atomic.rs',
    'crates/sf-conformance/src/regression_receipt/environment.rs',
    'crates/sf-conformance/src/regression_receipt/format.rs',
    'crates/sf-conformance/src/regression_receipt/mod.rs',
    'crates/sf-conformance/src/regression_receipt/model.rs',
    'crates/sf-conformance/src/regression_receipt/path.rs',
    'crates/sf-conformance/src/regression_receipt/runner.rs',
    'crates/sf-conformance/src/regression_receipt/tests.rs',
    'crates/sf-conformance/src/regression_receipt/tests/invariants.rs',
    'crates/sf-conformance/src/runner.rs',
    'crates/sf-conformance/src/rust_closure_receipt.rs',
    'crates/sf-conformance/src/rust_closure_receipt/authority.rs',
    'crates/sf-conformance/src/rust_closure_receipt/controlled.rs',
    'crates/sf-conformance/src/rust_closure_receipt/controlled_tests.rs',
    'crates/sf-conformance/src/rust_closure_receipt/controlled_tool.rs',
    'crates/sf-conformance/src/rust_closure_receipt/features.rs',
    'crates/sf-conformance/src/rust_closure_receipt/format.rs',
    'crates/sf-conformance/src/rust_closure_receipt/metadata.rs',
    'crates/sf-conformance/src/rust_closure_receipt/origin.rs',
    'crates/sf-conformance/src/rust_closure_receipt/platform.rs',
    'crates/sf-conformance/src/rust_closure_receipt/process.rs',
    'crates/sf-conformance/src/rust_closure_receipt/tests.rs',
    'crates/sf-conformance/src/rust_closure_receipt/tree.rs',
    'crates/sf-conformance/src/sealed_suite.rs',
    'crates/sf-conformance/src/sqlite.rs',
    'crates/sf-conformance/tests/binary_artifact_receipt.rs',
    'crates/sf-conformance/tests/capability_matrix.rs',
    'crates/sf-conformance/tests/differential_graphs.rs',
    'crates/sf-conformance/tests/differential_paths.rs',
    'crates/sf-conformance/tests/differential_star.rs',
    'crates/sf-conformance/tests/differential_tree.rs',
    'crates/sf-conformance/tests/rdb2rdf_execution_receipt.rs',
    'crates/sf-conformance/tests/rdb2rdf_inventory.rs',
    'crates/sf-conformance/tests/rdb2rdf_runner_seal.rs',
    'crates/sf-conformance/tests/regression_baseline_cli.rs',
    'crates/sf-conformance/tests/rust_closure_receipt.rs',
    'crates/sf-conformance/tests/w3c_pg_suite.rs',
    'crates/sf-core/Cargo.toml',
    'crates/sf-mapping/Cargo.toml',
    'crates/sf-serve/Cargo.toml',
    'crates/sf-serve/tests/endpoint.rs',
    'crates/sf-sparql/Cargo.toml',
    'crates/sf-sparql/tests/e2e.rs',
    'crates/sf-sql/Cargo.toml',
    'docs/adr/ADR-0001-semantic-fabric-rust-data-fabric.md',
    'docs/adr/ADR-0002-implementation-scope-rdbms-both-modes.md',
    'docs/adr/ADR-0003-shared-core-two-frontend-architecture.md',
    'docs/adr/ADR-0004-oxigraph-rdf-sparql-substrate.md',
    'docs/adr/ADR-0005-conformance-and-benchmark-harness.md',
    'docs/adr/ADR-0006-crate-layout-and-performance-model.md',
    'docs/adr/ADR-0007-sparql-to-sql-rewriting-strategy.md',
    'docs/adr/ADR-0008-reasoning-strategy.md',
    'docs/adr/ADR-0010-security-and-resource-governance.md',
    'docs/adr/ADR-0011-observability-and-configuration.md',
    'docs/adr/ADR-0012-test-strategy.md',
    'docs/adr/ADR-0014-production-hardening-backlog.md',
    'docs/adr/ADR-0015-datatype-dialect-correctness.md',
    'docs/adr/ADR-0017-provenance-lineage.md',
    'docs/adr/ADR-0018-security-edge.md',
    'docs/adr/ADR-0019-rdf-sparql-shacl-12-readiness.md',
    'docs/adr/ADR-0020-outstanding-sota-optimisations.md',
    'docs/adr/ADR-0021-ontop-parity-program.md',
    'docs/adr/ADR-0022-ws-g-ontop-optimizer-test-port.md',
    'docs/adr/ADR-0023-query-ir-architecture-flat-ucq-vs-iq-tree.md',
    'docs/adr/ADR-0024-executor-backend-abstraction.md',
    'docs/adr/ADR-0025-ontop-parity-residue-closure.md',
    'docs/adr/ADR-0026-agentic-qe-fleet-adoption.md',
    'docs/adr/ADR-0027-qe-fleet-load-test-plan.md',
    'docs/adr/ADR-0028-full-corpus-audit-ontop-parity-ecosystem-gaps-sparql12-coverage.md',
    'docs/adr/ADR-0029-rdf-star-mapping-extension-rml-star-vocabulary-basic-encoding.md',
    'docs/adr/ADR-0030-metaharness-darwin-mode-dev-process-adoption.md',
    'docs/adr/ADR-0031-rdf-star-query-rewrite-quoted-triple-patterns-basic-encoding.md',
    'docs/adr/ADR-0032-rdf-12-soundness-completeness-native-reification.md',
    'docs/adr/ADR-0033-path-as-derived-table-join-composition.md',
    'docs/adr/ADR-0034-virtual-graph-set-semantics-bgp-dedup.md',
    'docs/adr/ADR-0035-variable-graph-querying.md',
    'docs/adr/ADR-0036-correctness-first-open-issue-remediation.md',
    'docs/adr/ADR-0037-dual-host-ruflo-engineering-metaharness.md',
    'docs/adr/ADR-0038-sota-application-completion-programme.md',
    'docs/adr/ADR-0039-minimal-production-serving-artifact.md',
    'docs/adr/ADR-0040-bounded-federated-global-operators-and-spill.md',
    'docs/adr/ADR-0041-manifest-bound-controlled-observational-evidence-capture.md',
    'docs/adr/ADR-0042-witnessed-single-use-capture-supervisor-protocol.md',
    'docs/adr/ADR-0043-postgresql-supervisor-registration-state-and-dormant-adapter.md',
    'docs/adr/ADR-0044-postgresql-supervisor-catalogue-contract.md',
    'docs/adr/ADR-0045-canonical-postgresql-supervisor-catalogue-oracle-representation.md',
    'docs/adr/ADR-0046-sealed-postgresql-supervisor-migration-authority-bundle.md',
    'docs/capability-matrix.json',
    'docs/capability-matrix.md',
    'docs/plans/open-issues-ruflo-metaharness-implementation-plan.md',
    'docs/plans/sota-application-completion-programme.md',
    'harness-plan.json',
    'repo-profile.json',
    'rust-toolchain.toml',
    'scratch/sqlx-spike/Cargo.toml',
    'tests/capabilities/catalog-v1.json',
    'tests/capabilities/schema-v1.json',
    'tests/rust-dependency-closure.tsv',
    'tests/sparql/protocol/inventory.tsv',
    'tests/sparql/protocol/sqlite-expected-regression-baseline.tsv',
    'tests/sparql/query/inventory.tsv',
    'tests/sparql/query/sqlite-expected-regression-baseline.tsv',
    'tests/w3c/rdb2rdf/inventory.tsv',
    'tests/w3c/rdb2rdf/postgresql-execution-receipt.tsv',
    'tests/w3c/rdb2rdf/sqlite-execution-receipt.tsv',
  ],
  environment: {
    allow: [
      'PATH', 'HOME', 'TMPDIR', 'LANG', 'LC_ALL', 'TERM', 'COLORTERM', 'CI',
      'GIT_CONFIG_NOSYSTEM', 'CARGO_HOME', 'CARGO_INCREMENTAL', 'CARGO_NET_OFFLINE',
      'CARGO_TARGET_DIR', 'SYSTEMROOT', 'COMSPEC', 'PATHEXT', 'WINDIR',
    ],
    denyExact: [
      'OPENAI_API_KEY', 'ANTHROPIC_API_KEY', 'OPENROUTER_API_KEY', 'REQUESTY_API_KEY',
      'HTTP_PROXY', 'HTTPS_PROXY', 'ALL_PROXY', 'NO_PROXY',
    ],
    denyPrefixes: ['OPENROUTER_', 'REQUESTY_'],
    denySuffixes: ['_BASE_URL', '_API_BASE', '_PROXY'],
  },
  limits: {
    maxTimeoutMs: 1_800_000,
    maxOutputBytes: 10_000_000,
    maxNewFileLines: 500,
    terminationGraceMs: 500,
  },
  evolution: {
    minimumTrainingTasks: 5,
    minimumSealedHoldouts: 5,
  },
});

export interface EvolutionEligibility {
  eligible: boolean;
  trainingTasks: number;
  sealedHoldouts: number;
  reason: string;
}

export function checkEvolutionEligibility(
  trainingTaskIds: readonly string[],
  sealedHoldoutIds: readonly string[],
): EvolutionEligibility {
  const training = new Set(trainingTaskIds);
  const holdouts = new Set(sealedHoldoutIds);
  const overlap = [...training].some((id) => holdouts.has(id));
  const opaque = [...training, ...holdouts].every((id) => /^[A-Za-z0-9_-]{8,128}$/.test(id));
  const eligible = training.size >= 5 && holdouts.size >= 5 && !overlap && opaque;
  return {
    eligible,
    trainingTasks: training.size,
    sealedHoldouts: holdouts.size,
    reason: eligible
      ? '5+5 distinct opaque task IDs present; evaluator eligibility still requires independent review'
      : 'requires at least 5 distinct training IDs and 5 distinct sealed holdout IDs with no overlap',
  };
}
