// SPDX-License-Identifier: MIT

export const PROGRAMME_CAPTURE_TEST_PROTECTED_PATHS_V1 = Object.freeze([
  'coding-harness/__tests__/programme-capture-claim-io-v1.test.ts',
  'coding-harness/__tests__/programme-capture-claim-record-v1.test.ts',
  'coding-harness/__tests__/programme-capture-git-v1.test.ts',
  'coding-harness/__tests__/programme-capture-host-capabilities-v1.test.ts',
  'coding-harness/__tests__/programme-capture-host-preflight-v1.test.ts',
  'coding-harness/__tests__/programme-capture-input-attestation-v1.test.ts',
  'coding-harness/__tests__/programme-capture-private-source-v1.test.ts',
  'coding-harness/__tests__/programme-capture-state-v1.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-authority-config-v2.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-authority-transition-v2.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-capabilities-v1.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-capabilities-v2.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-checkpoint-kat-v1.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-checkpoint-v1.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-claim-v1.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-kat-v1.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-log-proof-kat-v1.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-log-proof-v1.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-merkle-v1.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-run-event-kat-v2.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-run-event-transition-v2.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-run-event-v2.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-run-event-verifier-v2.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-service-client-v2.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-service-codecs-v2.test.ts',
  'coding-harness/__tests__/programme-capture-supervisor-transport-v2.test.ts',
  'coding-harness/__tests__/programme-capture-task-v1.test.ts',
] as const);

export const PROGRAMME_CAPTURE_TEST_SUPPORT_PROTECTED_PATHS_V1 = Object.freeze([
  'coding-harness/__tests__/programme-capture-supervisor-run-event-v2-fixtures.ts',
] as const);

export const PROGRAMME_CAPTURE_SOURCE_PROTECTED_PATHS_V1 = Object.freeze([
  'coding-harness/src/programme-capture-claim-io-v1.ts',
  'coding-harness/src/programme-capture-claim-key-v1.ts',
  'coding-harness/src/programme-capture-claim-record-v1.ts',
  'coding-harness/src/programme-capture-config-v1.ts',
  'coding-harness/src/programme-capture-git-v1.ts',
  'coding-harness/src/programme-capture-host-authority-v1.ts',
  'coding-harness/src/programme-capture-host-observation-v1.ts',
  'coding-harness/src/programme-capture-host-preflight-v1.ts',
  'coding-harness/src/programme-capture-input-attestation-record-v1.ts',
  'coding-harness/src/programme-capture-input-attestation-v1.ts',
  'coding-harness/src/programme-capture-private-source-fs-v1.ts',
  'coding-harness/src/programme-capture-private-source-v1.ts',
  'coding-harness/src/programme-capture-protected-paths-v1.ts',
  'coding-harness/src/programme-capture-runner-profile-v1.ts',
  'coding-harness/src/programme-capture-state-v1.ts',
  'coding-harness/src/programme-capture-supervisor-authority-config-v2.ts',
  'coding-harness/src/programme-capture-supervisor-authority-transition-v2.ts',
  'coding-harness/src/programme-capture-supervisor-checkpoint-v1.ts',
  'coding-harness/src/programme-capture-supervisor-claim-v1.ts',
  'coding-harness/src/programme-capture-supervisor-codec-v1.ts',
  'coding-harness/src/programme-capture-supervisor-crypto-v1.ts',
  'coding-harness/src/programme-capture-supervisor-log-proof-codec-v1.ts',
  'coding-harness/src/programme-capture-supervisor-log-proof-v1.ts',
  'coding-harness/src/programme-capture-supervisor-merkle-v1.ts',
  'coding-harness/src/programme-capture-supervisor-public-commitment-v2.ts',
  'coding-harness/src/programme-capture-supervisor-registration-request-v2.ts',
  'coding-harness/src/programme-capture-supervisor-run-event-builder-v2.ts',
  'coding-harness/src/programme-capture-supervisor-run-event-body-v2.ts',
  'coding-harness/src/programme-capture-supervisor-run-event-codec-v2.ts',
  'coding-harness/src/programme-capture-supervisor-run-event-contracts-v2.ts',
  'coding-harness/src/programme-capture-supervisor-run-event-transition-v2.ts',
  'coding-harness/src/programme-capture-supervisor-run-event-verifier-v2.ts',
  'coding-harness/src/programme-capture-supervisor-service-client-v2.ts',
  'coding-harness/src/programme-capture-supervisor-service-result-v2.ts',
  'coding-harness/src/programme-capture-supervisor-transport-response-v2.ts',
  'coding-harness/src/programme-capture-task-v1.ts',
] as const);

export const PROGRAMME_CAPTURE_SUPERVISOR_SERVICE_PACKAGE_PROTECTED_PATHS_V1 = Object.freeze([
  'coding-harness/supervisor-service/.gitignore',
  'coding-harness/supervisor-service/.service/artifact.json',
  'coding-harness/supervisor-service/.service/manifest.json',
  'coding-harness/supervisor-service/__tests__/package-boundary.test.ts',
  'coding-harness/supervisor-service/__tests__/readiness.test.ts',
  'coding-harness/supervisor-service/__tests__/sealed-build.test.ts',
  'coding-harness/supervisor-service/package-lock.json',
  'coding-harness/supervisor-service/package.json',
  'coding-harness/supervisor-service/scripts/artifact-lib.mjs',
  'coding-harness/supervisor-service/scripts/build.mjs',
  'coding-harness/supervisor-service/scripts/deny-publish.mjs',
  'coding-harness/supervisor-service/scripts/verify-artifact.mjs',
  'coding-harness/supervisor-service/src/index.ts',
  'coding-harness/supervisor-service/src/readiness.ts',
  'coding-harness/supervisor-service/tsconfig.json',
] as const);
