//! Deterministic public artifacts derived from the capability catalog.

use std::fmt::Write as _;

use serde::Serialize;
use serde_json::json;

use crate::capability_catalog::{compact_json, status_counts, LoadedCatalog};
use crate::capability_model::{Catalog, ClaimKind, Status};

macro_rules! writeln {
    ($($argument:tt)*) => {
        std::writeln!($($argument)*).map_err(|error| error.to_string())
    };
}

pub const GENERATED_JSON_PATH: &str = "docs/capability-matrix.json";
pub const GENERATED_MARKDOWN_PATH: &str = "docs/capability-matrix.md";
pub const README_PATH: &str = "README.md";
pub const README_START: &str = "<!-- capability-matrix:start -->";
pub const README_END: &str = "<!-- capability-matrix:end -->";

const FORBIDDEN_MANUAL_CLAIMS: &[&str] = &[
    "The public serving path currently admits **SQLite, PostgreSQL, and MySQL**.",
    "SPARQL 1.2 BGPs, joins, OPTIONAL, UNION, MINUS, FILTER, EXISTS/NOT EXISTS,\n  BIND, VALUES, subqueries, aggregation, ordering, slicing, and all four query\n  forms through the supported plan shapes.",
];

#[derive(Debug, Clone)]
pub struct GeneratedArtifacts {
    pub json: String,
    pub markdown: String,
    pub readme: String,
}

pub fn render(loaded: &LoadedCatalog, current_readme: &str) -> Result<GeneratedArtifacts, String> {
    validate_manual_readme(current_readme)?;
    Ok(GeneratedArtifacts {
        json: render_json(loaded)?,
        markdown: render_markdown(loaded)?,
        readme: replace_readme_block(current_readme, &render_readme_block(loaded)),
    })
}

pub fn render_json(loaded: &LoadedCatalog) -> Result<String, String> {
    let counts = status_counts(&loaded.catalog);
    compact_json(&json!({
        "schemaVersion": 1,
        "asOf": loaded.catalog.as_of,
        "generatedFrom": crate::capability_catalog::CATALOG_PATH,
        "catalogSha256": loaded.catalog_sha256,
        "schemaSha256": loaded.schema_sha256,
        "statusCounts": {
            "admitted": counts.get(&Status::Admitted).copied().unwrap_or(0),
            "implemented": counts.get(&Status::Implemented).copied().unwrap_or(0),
            "planned": counts.get(&Status::Planned).copied().unwrap_or(0),
            "unsupported": counts.get(&Status::Unsupported).copied().unwrap_or(0),
        },
        "catalog": loaded.catalog,
    }))
}

pub fn render_markdown(loaded: &LoadedCatalog) -> Result<String, String> {
    let catalog = &loaded.catalog;
    let counts = status_counts(catalog);
    let mut output = String::new();
    writeln!(output, "# Capability, backend and standards matrix\n")?;
    writeln!(
        output,
        "> Generated from `{}` (SHA-256 `{}`) as of {}. Do not edit this file directly.\n",
        crate::capability_catalog::CATALOG_PATH,
        loaded.catalog_sha256,
        catalog.as_of
    )?;
    writeln!(
        output,
        "Status is evidence-scoped: `implemented` does not mean production `admitted`."
    )?;
    writeln!(
        output,
        "The current matrix contains **{} admitted**, **{} implemented**, **{} planned**, and **{} unsupported** cells.\n",
        counts.get(&Status::Admitted).copied().unwrap_or(0),
        counts.get(&Status::Implemented).copied().unwrap_or(0),
        counts.get(&Status::Planned).copied().unwrap_or(0),
        counts.get(&Status::Unsupported).copied().unwrap_or(0),
    )?;

    writeln!(output, "## Dated standards references\n")?;
    writeln!(
        output,
        "These URL, date, byte-length, and digest records describe retrieved reference bytes."
    )?;
    writeln!(
        output,
        "The specifications are not vendored, fetched, or treated as executable evidence by `--check`.\n"
    )?;
    writeln!(
        output,
        "| ID | Snapshot | Status | Classification | SHA-256 |"
    )?;
    writeln!(output, "|---|---|---|---|---|")?;
    for standard in &catalog.standards {
        writeln!(
            output,
            "| [{}]({}) | {} | {} | {} | `{}` |",
            table(&standard.title),
            standard.url,
            standard.snapshot_date,
            table(&standard.status),
            enum_label(standard.classification)?,
            standard.sha256
        )?;
    }
    writeln!(output)?;

    writeln!(output, "## Capability cells\n")?;
    writeln!(
        output,
        "| ID | Surface | Capability | Backend | Status | Verification | Exact | Bounded | Advertisable | Qualification |"
    )?;
    writeln!(output, "|---|---|---|---|---|---|---:|---:|---:|---|")?;
    for cell in &catalog.cells {
        let profile = find_profile(catalog, &cell.profile_id)?;
        let backend = catalog
            .backends
            .iter()
            .find(|backend| backend.id == cell.backend_id)
            .ok_or_else(|| format!("missing backend {} while rendering", cell.backend_id))?;
        writeln!(
            output,
            "| {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |",
            cell.id,
            enum_label(profile.surface)?,
            table(&profile.capability),
            table(&backend.label),
            enum_label(cell.status)?,
            enum_label(cell.verification)?,
            yes_no(cell.semantic_exact),
            yes_no(cell.bounded),
            yes_no(cell.advertisable),
            table(&cell.qualification)
        )?;
    }
    writeln!(output)?;

    writeln!(output, "## Evidence registry\n")?;
    writeln!(
        output,
        "| ID | Domain | Verification | Required | Path / selector | Command |"
    )?;
    writeln!(output, "|---|---|---|---:|---|---|")?;
    for evidence in &catalog.evidence {
        let command = evidence
            .command_id
            .as_deref()
            .and_then(|id| catalog.commands.iter().find(|command| command.id == id))
            .map(|command| format!("`{}`", table(&command.argv)))
            .unwrap_or_else(|| "None (decision evidence)".to_owned());
        writeln!(
            output,
            "| {} | {} | {} | {} | `{}` — {} | {} |",
            evidence.id,
            enum_label(evidence.domain)?,
            enum_label(evidence.verification)?,
            yes_no(evidence.required),
            evidence.path,
            table(&evidence.selector),
            command
        )?;
    }
    writeln!(output)?;

    writeln!(output, "## Release-blocking limitations\n")?;
    for limitation in catalog
        .limitations
        .iter()
        .filter(|limitation| limitation.release_blocking)
    {
        writeln!(
            output,
            "- **{} ({})** — {}",
            limitation.id, limitation.adr, limitation.summary
        )?;
    }
    writeln!(output)?;
    writeln!(output, "## Scope exclusions\n")?;
    for exclusion in &catalog.scope_exclusions {
        writeln!(output, "- **{}** — {}", exclusion.id, exclusion.text)?;
    }
    Ok(output)
}

pub fn render_readme_block(loaded: &LoadedCatalog) -> String {
    let mut output = String::new();
    writeln!(output, "{README_START}").expect("String writes cannot fail");
    writeln!(output, "## Evidence-scoped capability status\n").expect("String writes cannot fail");
    writeln!(
        output,
        "As of {}, the generated catalog records:\n",
        loaded.catalog.as_of
    )
    .expect("String writes cannot fail");
    for claim in &loaded.catalog.claims {
        let prefix = match claim.kind {
            ClaimKind::Current => "Current",
            ClaimKind::Qualification => "Qualified",
            ClaimKind::Limitation => "Limitation",
        };
        writeln!(output, "- **{prefix}:** {}", claim.text).expect("String writes cannot fail");
    }
    writeln!(
        output,
        "\nSee the generated [capability/backend/standards matrix](docs/capability-matrix.md)"
    )
    .expect("String writes cannot fail");
    writeln!(
        output,
        "for per-cell evidence grades, exact limitations, and dated standards reference metadata.\n"
    )
    .expect("String writes cannot fail");
    writeln!(output, "{README_END}").expect("String writes cannot fail");
    output
}

pub fn replace_readme_block(readme: &str, block: &str) -> String {
    let Some(start) = readme.find(README_START) else {
        return readme.to_owned();
    };
    let Some(relative_end) = readme[start..].find(README_END) else {
        return readme.to_owned();
    };
    let end = start + relative_end + README_END.len();
    format!("{}{}{}", &readme[..start], block.trim_end(), &readme[end..])
}

pub fn validate_manual_readme(readme: &str) -> Result<(), String> {
    if readme.matches(README_START).count() != 1 || readme.matches(README_END).count() != 1 {
        return Err("README must contain exactly one capability-matrix marker pair".to_owned());
    }
    let start = readme
        .find(README_START)
        .ok_or_else(|| "README capability marker is missing".to_owned())?;
    let end = readme
        .find(README_END)
        .ok_or_else(|| "README capability end marker is missing".to_owned())?;
    if start >= end {
        return Err("README capability markers are out of order".to_owned());
    }
    let mut manual = String::with_capacity(readme.len());
    manual.push_str(&readme[..start]);
    manual.push_str(&readme[end + README_END.len()..]);
    if let Some(claim) = FORBIDDEN_MANUAL_CLAIMS
        .iter()
        .find(|claim| manual.contains(**claim))
    {
        return Err(format!(
            "README contains a forbidden unqualified manual claim: {claim}"
        ));
    }
    Ok(())
}

fn find_profile<'a>(
    catalog: &'a Catalog,
    id: &str,
) -> Result<&'a crate::capability_model::Profile, String> {
    catalog
        .profiles
        .iter()
        .find(|profile| profile.id == id)
        .ok_or_else(|| format!("missing profile {id} while rendering"))
}

fn enum_label(value: impl Serialize) -> Result<String, String> {
    serde_json::to_value(value)
        .map_err(|error| format!("serialize catalog enum: {error}"))?
        .as_str()
        .map(str::to_owned)
        .ok_or_else(|| "catalog enum did not serialize as a string".to_owned())
}

fn table(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

fn yes_no(value: bool) -> &'static str {
    if value {
        "yes"
    } else {
        "no"
    }
}
